wall_follower:
  ros__parameters:
    scan_topic: "/scan"
    drive_topic: "/vesc/high_level/input/nav_0"
    side: -1
    velocity: 0.5
    desired_distance: 0.5
    safety_topic: "/vesc/low_level/input/safety"
    drive_sub_topic: "/vesc/low_level/ackermann_cmd"