wall_follower:
  ros__parameters:
    scan_topic: "/scan"
    drive_topic: "/vesc/low_level/input/navigation"
    side: -1
    velocity: 1.0
    desired_distance: 1.
    safety_topic: "/vesc/low_level/input/safety"
    drive_sub_topic: "/vesc/low_level/ackermann_cmd"